### ISSUE TITLE
Airport data up-to-date

### ISSUE THREAD

**Issue by luizpedone** [jbrooksuk/JSON-Airports#3]
Hi James! First of all, thanks for making this data public!

I'm opening this issue just to know if the data here are up-to-date and if you have plans to update it soon. It seems that the JSON wasn't updated for more than a year, so I'd like to know if you have new stuff to put there and if you will do it.

Thanks! =)

**Comment by jbrooksuk** [comment]
Hey @luizpedone I keep missing issues. I'm really sorry!

**Comment by luizpedone** [comment]
Hey @jbrooksuk! No problem! =)

Do you have a newer version of the airport data? If you do have, Maybe would be nice to add it here.

If you need any help handling the PRs/issues. Let me know. I'll be glad to help.

**Comment by jbrooksuk** [comment]
This is the latest version I have I'm afraid.
